apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: flask-app
  labels:
    app: flask-app
spec:
  type: LoadBalancer          # Expose externally on Windows / Minikube
  selector:
    app: flask-app
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  sessionAffinity: None       # No session stickiness; Flask is stateless
